name: GHAS Unique Active Comitters

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unique-active-committers:
    name: Unique Active Committers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github-token: ${{ secrets.TOKEN }}
          organization: 'octodemo'